name: CI Workflow

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  lint-compile-prove:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      {%- if circuitType == "circom" %}
          cache: npm
      {%- endif %}

      - name: Store the Current Branch Name
        run: |
          {% raw %}if [ "${{ github.event_name }}" = "pull_request" ]; then{% endraw %}
            {% raw %}echo "BRANCH_NAME=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV{% endraw %}
          else
            {% raw %}BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,refs/heads/,,'){% endraw %}
            echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          fi

      - name: Install Sindri CLI Tool
        run: |
          npm install -g sindri@latest

      {%- if circuitType == "circom" %}

      - name: Install JavaScript Dependencies
        run: |
          npm ci
      {%- endif %}

      - name: Lint Circuit
        run: |
          sindri lint

      - name: Compile the Circuit
        run: |
          sindri deploy --tag "${BRANCH_NAME}"
        env:
          SINDRI_API_KEY: {% raw %}${{ secrets.SINDRI_API_KEY }}{% endraw %}


      - name: Create and Verify a Proof
        run: |
          sindri proof create --verify --tag "${BRANCH_NAME}"
        env:
          SINDRI_API_KEY: {% raw %}${{ secrets.SINDRI_API_KEY }}{% endraw %}

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    needs: [lint-compile-prove]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      {%- if circuitType == "circom" %}
          cache: npm
      {%- endif %}

      - name: Install Sindri CLI Tool
        run: |
          npm install -g sindri@latest

      {%- if circuitType == "circom" %}

      - name: Install JavaScript Dependencies
        run: |
          npm ci
      {%- endif %}

      - name: Deploy the Circuit
        run: |
          sindri deploy
        env:
          SINDRI_API_KEY: {% raw %}${{ secrets.SINDRI_API_KEY }}{% endraw %}
