name: CI Workflows

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Dependencies
        run: |
          yarn install --immutable

      - name: Lint
        if: success() || failure()
        run: |
          yarn lint

      - name: Typecheck
        if: success() || failure()
        run: |
          yarn typecheck

      - name: Build
        if: success() || failure()
        run: |
          yarn build

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: [lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Extract Version from Tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Update package.json Version
        run: npm version --no-git-tag-version $VERSION

      - name: Publish to NPM
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
