name: Check Codebase

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Dependencies
        run: |
          yarn install --immutable

      - name: Lint
        if: success() || failure()
        run: |
          yarn lint

      - name: Build
        if: success() || failure()
        run: |
          yarn build
